### ISSUE TITLE
How do I change the accent coloring provided by the dark theme?

### ISSUE THREAD

**Issue by asyagelski** [Dirkster99/MLib#4]
![MetroWindowAccentColors](https://user-images.githubusercontent.com/8888989/75910007-1ce32e80-5e1b-11ea-901b-e3413a2922d4.png)

The border of the window I've created is blue, along with the resizing grip. I can't seem to reference MWindowLib.Themes in XAML, and because of my experience with styling in XAML I'm pretty much stuck after that haha.

Thanks in advance! I use multiple libraries of yours and find them all very useful.

**Comment by Dirkster99** [comment]
There is a test client that implements changing the accent color via a [Color Picker tool window](https://github.com/Dirkster99/AvalonDock/wiki/WPF-VS-2013-Dark-Light-Demo-Client) 
[MLibTest](https://github.com/Dirkster99/AvalonDock/tree/master/source/MLibTest/MLibTest)

This is a high level MVVM compliant test client that might be useful for your purpose. Relevant classes for handling themes are certainly:
- [MLibTest.ViewModels.ThemeViewModel](https://github.com/Dirkster99/AvalonDock/blob/master/source/MLibTest/MLibTest/ViewModels/ThemeViewModel.cs)
- [MLibTest.ViewModels.ThemeDefinitionViewModel](https://github.com/Dirkster99/AvalonDock/blob/master/source/MLibTest/MLibTest/ViewModels/ThemeDefinitionViewModel.cs)

The change of AccentColor is implemented as a sample via `ICommand ResetAccentColorCommand` in:
- [MLibTest.Demos.ViewModels.Tools.ColorPickerViewModel](https://github.com/Dirkster99/AvalonDock/blob/35cf0cde705984d301df0f5d224d8da7cdbf84d3/source/MLibTest/MLibTest/Demos/ViewModels/Tools/ColorPickerViewModel.cs#L102)

I hope this helps you answering your questions, if not feel free to ask further. To better understand the design principals used here I also suggest to read the linked CodeProject article in the MLib Readme page.

Thanx for your good feedback and feel free to suggest PRs for improvements or set a STAR here or there to support open source projects in a visible and verifyable way for others :-)

Cheers Dirk
