### ISSUE TITLE
How to get main window to take style?

### ISSUE THREAD

**Issue by sphet** [Dirkster99/MLib#6]
In App.xml I wrote:

        protected override void OnStartup(StartupEventArgs e)
        {
            themeInfos = AppearanceManager.GetInstance().CreateThemeInfos();
            AppearanceManager.GetInstance().SetDefaultThemes(themeInfos, true);
            AppearanceManager.GetInstance().SetTheme(themeInfos, "Dark", Colors.Red);
            base.OnStartup(e);
        }

And in MainWindows.xaml:

        <mWindowLib:MetroWindow ...>
                 ...
                 <Button Content="Hello"/>
        </mWindowLib:MetroWindow>

And while the button is dark, the window is not. I have MLib and MWindowLib packages installed.

What do I need to do to coax the window to change to use the style?

**Comment by Dirkster99** [comment]
You also need to load the [styles and brushes you intent to use](https://github.com/Dirkster99/MLib/blob/e13bd73ad6f20e5cf9e3ef69f52faa91deed7ff5/source/MDemo/ViewModels/AppLifeCycleViewModel.cs#L153).

The demo app is doing it through the linked viewmodel but you could also use App.xaml resources or other means of loading the right xaml resources....
