### ISSUE TITLE
Minimal Setup To integrate with Mahapps

### ISSUE THREAD

**Issue by Offline-R503B** [Dirkster99/MLib#8]
What would the minimal setup be to set the accent color to the accent color of mahapps ?

This would purely be to style the Avalondock and its "tools" along with the rest of the application.

Thanks in advance!

**Comment by Dirkster99** [comment]
you could probably use the VS2013 Dark/Light themes and set the accent color as shown in the MLibTest app in the repository (but without using MLib). I am not using Mahapps so I cannot give you a better advice, sorry.
